name: build ios
on: 
  pull_request: 
    branches: flutter
  push:
    branches: flutter

jobs:
  build_ios:
    name: "Build iOS"
    runs-on: macOS-latest
    steps:
      - name: Checkout repository      
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"
      - name: Build iOS
        run: flutter build ios --simulator
      